default:
  # Websocket server setup, see script/websocket_server.rb
  # Enable extensive logging to websocket server.
  socket_debug : false
  
  # Websocket host, leave as 0.0.0.0 unless you know what you are doing
  socket_host: 0.0.0.0
  
  # File containing pid of running script/websocket_server.rb
  socket_pidfile: "tmp/pids/caritas-wss.pid"
  
  # Websocket port, should normally be 8080 or 8081.
  socket_port: 8080
  socket_collection_name: 'websocket'

  # Secure websocket confguration (wss://)
  # requires SSL cert and key
  socket_secure: false
  socket_private_key_location: '/full/path/to/file.key'
  socket_cert_chain_location: '/full/path/to/cert_chain.crt'