require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PartnersController do

  def mock_partner(stubs={})
    @mock_partner ||= mock_model(Partner, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all partners as @partners" do
      Partner.stub(:all) { [mock_partner] }
      get :index
      assigns(:partners).should eq([mock_partner])
    end
  end

  describe "GET show" do
    it "assigns the requested partner as @partner" do
      Partner.stub(:find).with("37") { mock_partner }
      get :show, :id => "37"
      assigns(:partner).should be(mock_partner)
    end
  end

  describe "GET new" do
    it "assigns a new partner as @partner" do
      Partner.stub(:new) { mock_partner }
      get :new
      assigns(:partner).should be(mock_partner)
    end
  end

  describe "GET edit" do
    it "assigns the requested partner as @partner" do
      Partner.stub(:find).with("37") { mock_partner }
      get :edit, :id => "37"
      assigns(:partner).should be(mock_partner)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created partner as @partner" do
        Partner.stub(:new).with({'these' => 'params'}) { mock_partner(:save => true) }
        post :create, :partner => {'these' => 'params'}
        assigns(:partner).should be(mock_partner)
      end

      it "redirects to the created partner" do
        Partner.stub(:new) { mock_partner(:save => true) }
        post :create, :partner => {}
        response.should redirect_to(partner_url(mock_partner))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved partner as @partner" do
        Partner.stub(:new).with({'these' => 'params'}) { mock_partner(:save => false) }
        post :create, :partner => {'these' => 'params'}
        assigns(:partner).should be(mock_partner)
      end

      it "re-renders the 'new' template" do
        Partner.stub(:new) { mock_partner(:save => false) }
        post :create, :partner => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested partner" do
        Partner.stub(:find).with("37") { mock_partner }
        mock_partner.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :partner => {'these' => 'params'}
      end

      it "assigns the requested partner as @partner" do
        Partner.stub(:find) { mock_partner(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:partner).should be(mock_partner)
      end

      it "redirects to the partner" do
        Partner.stub(:find) { mock_partner(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(partner_url(mock_partner))
      end
    end

    describe "with invalid params" do
      it "assigns the partner as @partner" do
        Partner.stub(:find) { mock_partner(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:partner).should be(mock_partner)
      end

      it "re-renders the 'edit' template" do
        Partner.stub(:find) { mock_partner(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested partner" do
      Partner.stub(:find).with("37") { mock_partner }
      mock_partner.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the partners list" do
      Partner.stub(:find) { mock_partner }
      delete :destroy, :id => "1"
      response.should redirect_to(partners_url)
    end
  end

end
